index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
