index:
    path: /
    controller: App\Controller\DefaultController::index

app_email_confirmation_required:
    path: //email/confirmation/required
    controller: App\Controller\EmailConfirmationRequiredController::index

contact:
    path: /contact
    controller: App\Controller\ContactController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
